export type QuestionType = "text" | "textarea" | "yesno" | "email" | "date";

export interface Question {
  id: string;
  label: string;
  subtitle?: string;
  type: QuestionType;
  required?: boolean;
  placeholder?: string;
  conditionField?: string;
  conditionValue?: string;
}

export interface SpeechTypeConfig {
  id: string;
  title: string;
  description: string;
  questions: Question[];
}

export const bestManQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Wilson" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "aboutYou", label: "How old are you, what's your job, where do you live etc", type: "textarea", placeholder: "Tell us a bit about yourself, this helps us write in your voice" },
  { id: "groomName", label: "The groom's name?", type: "text", required: true, placeholder: "e.g. Tom" },
  { id: "howKnowGroom", label: "How do you know the groom?", type: "textarea", required: true, placeholder: "e.g. We've been best friends since primary school" },
  { id: "groomJob", label: "What does he do for a living?", type: "text", placeholder: "e.g. Software engineer" },
  { id: "firstMet", label: "Do you remember the first time you met?", type: "textarea", placeholder: "Paint us the picture... where, when, first impressions" },
  { id: "passions", label: "What are his passions?", type: "textarea", placeholder: "e.g. Football, cooking, terrible dad jokes..." },
  { id: "dislikes", label: "What does he really not like?", type: "textarea", placeholder: "e.g. Mornings, olives, losing at FIFA..." },
  { id: "youngerCharacter", label: "What type of character was he when younger?", type: "textarea", placeholder: "Shy? Class clown? Always in trouble?" },
  { id: "grownCharacter", label: "What type of character has he grown into?", type: "textarea", placeholder: "Reliable? Still chaotic? A great dad?" },
  { id: "wantedToBe", label: "What did he want to be when he was younger?", type: "text", placeholder: "e.g. Astronaut, footballer, accountant (seriously)" },
  { id: "stories", label: "Any stories from school/college/work/home?", subtitle: "The more detail the better, these become the heart of your speech", type: "textarea", required: true, placeholder: "Share as many as you like. Funny, touching, embarrassing, all gold." },
  { id: "likeSchool", label: "Did the groom like school?", type: "yesno", required: true },
  { id: "university", label: "Did the groom go to university?", type: "yesno", required: true },
  { id: "biggestDisaster", label: "What is his biggest disaster?", subtitle: "Preferably funny", type: "textarea", placeholder: "The holiday that went wrong, the haircut, the cooking incident..." },
  { id: "hasChildren", label: "Does the groom have children?", type: "yesno", required: true },
  { id: "childrenNames", label: "Please give me their names", type: "text", conditionField: "hasChildren", conditionValue: "Yes", placeholder: "e.g. Lily, Max" },
  { id: "brideName", label: "What is the name of his bride?", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true, placeholder: "The full story, the more detail, the better the speech" },
  { id: "brideEffect", label: "What sort of effect has she had on him?", type: "textarea", placeholder: "How has he changed? What's different about him now?" },
  { id: "helpedYou", label: "In what ways has he helped you out in the past?", type: "textarea", placeholder: "Times he showed up for you, this adds real depth to the speech" },
];

export const groomQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. Tom" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Smith" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "brideName", label: "Your bride's name?", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "howMet", label: "How did you meet?", type: "textarea", required: true, placeholder: "The full story" },
  { id: "firstImpression", label: "What was your first impression of her?", type: "textarea", placeholder: "What did you think?" },
  { id: "whenKnew", label: "When did you know she was the one?", type: "textarea", placeholder: "The moment it clicked" },
  { id: "whatLove", label: "What do you love most about her?", type: "textarea", required: true, placeholder: "Be specific and personal" },
  { id: "proposal", label: "How did you propose?", type: "textarea", placeholder: "The full story" },
  { id: "herFamily", label: "Tell us about her family", type: "textarea", placeholder: "Her parents, siblings" },
  { id: "herParentsNames", label: "Names of her parents?", type: "text", placeholder: "e.g. John and Mary" },
  { id: "thankHerParents", label: "What do you want to thank her parents for?", type: "textarea", placeholder: "Raising her, welcoming you..." },
  { id: "yourParentsNames", label: "Names of your parents?", type: "text", placeholder: "e.g. David and Jane" },
  { id: "thankYourParents", label: "What do you want to thank your parents for?", type: "textarea", placeholder: "Their support, values..." },
  { id: "bestManName", label: "Best man's name?", type: "text", placeholder: "e.g. James" },
  { id: "thankBestMan", label: "What do you want to say about your best man?", type: "textarea", placeholder: "Funny stories, gratitude..." },
  { id: "bridesmaids", label: "Any special mention for the bridesmaids?", type: "textarea", placeholder: "How they look, their support..." },
  { id: "specialMentions", label: "Anyone else you want to thank?", type: "textarea", placeholder: "Family, friends who helped..." },
  { id: "hasChildren", label: "Do you have children?", type: "yesno", required: true },
  { id: "childrenNames", label: "What are their names?", type: "text", conditionField: "hasChildren", conditionValue: "Yes", placeholder: "e.g. Lily, Max" },
  { id: "absentFriends", label: "Would you like to make a toast to absent friends?", type: "yesno" },
  { id: "absentFriendsDetails", label: "Tell me about them", type: "textarea", conditionField: "absentFriends", conditionValue: "Yes", placeholder: "Who they are and why they matter" },
  { id: "futurePlans", label: "What are you most looking forward to in your future together?", type: "textarea", placeholder: "Dreams, plans, adventures..." },
  { id: "funnyStory", label: "A funny story about you and your bride?", type: "textarea", placeholder: "Something that captures your relationship" },
  { id: "weddingVenue", label: "Where are you getting married?", type: "text", placeholder: "e.g. St. Mary's Church, London" },
  { id: "honeymoon", label: "Where are you going on honeymoon?", type: "text", placeholder: "e.g. Amalfi Coast" },
  { id: "closingMessage", label: "Any final message you want to include?", type: "textarea", placeholder: "Your closing sentiment" },
];

export const brideQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Jones" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "groomName", label: "Your groom's name?", type: "text", required: true, placeholder: "e.g. Tom" },
  { id: "howMet", label: "How did you meet?", type: "textarea", required: true, placeholder: "The full story" },
  { id: "firstImpression", label: "What was your first impression of him?", type: "textarea", placeholder: "What did you think?" },
  { id: "whenKnew", label: "When did you know he was the one?", type: "textarea", placeholder: "The moment it clicked" },
  { id: "whatLove", label: "What do you love most about him?", type: "textarea", required: true, placeholder: "Be specific and personal" },
  { id: "proposal", label: "How did he propose?", type: "textarea", placeholder: "The full story" },
  { id: "hisFamily", label: "Tell us about his family", type: "textarea", placeholder: "His parents, siblings" },
  { id: "hisParentsNames", label: "Names of his parents?", type: "text", placeholder: "e.g. David and Jane" },
  { id: "thankHisParents", label: "What do you want to thank his parents for?", type: "textarea", placeholder: "Welcoming you, raising him..." },
  { id: "yourParentsNames", label: "Names of your parents?", type: "text", placeholder: "e.g. John and Mary" },
  { id: "thankYourParents", label: "What do you want to thank your parents for?", type: "textarea", placeholder: "Their support, love..." },
  { id: "maidOfHonour", label: "Maid of honour's name?", type: "text", placeholder: "e.g. Emma" },
  { id: "thankMaidOfHonour", label: "What do you want to say about your maid of honour?", type: "textarea", placeholder: "Funny stories, gratitude..." },
  { id: "specialMentions", label: "Anyone else you want to thank?", type: "textarea", placeholder: "Family, friends who helped..." },
  { id: "hasChildren", label: "Do you have children?", type: "yesno", required: true },
  { id: "childrenNames", label: "What are their names?", type: "text", conditionField: "hasChildren", conditionValue: "Yes" },
  { id: "absentFriends", label: "Would you like to make a toast to absent friends?", type: "yesno" },
  { id: "absentFriendsDetails", label: "Tell me about them", type: "textarea", conditionField: "absentFriends", conditionValue: "Yes", placeholder: "Who they are and why they matter" },
  { id: "futurePlans", label: "What are you most looking forward to in your future together?", type: "textarea", placeholder: "Dreams, plans, adventures..." },
  { id: "funnyStory", label: "A funny story about you and your groom?", type: "textarea", placeholder: "Something that captures your relationship" },
  { id: "closingMessage", label: "Any final message you want to include?", type: "textarea", placeholder: "Your closing sentiment" },
];

export const fatherOfBrideQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. John" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Smith" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "wifeName", label: "Your wife/partner's name?", type: "text", placeholder: "e.g. Mary" },
  { id: "stillMarried", label: "Are you still married?", type: "yesno", required: true },
  { id: "hasPartner", label: "Do you have a long term partner?", type: "yesno", conditionField: "stillMarried", conditionValue: "No" },
  { id: "partnerName", label: "What is your partner's name?", type: "text", conditionField: "hasPartner", conditionValue: "Yes" },
  { id: "daughterName", label: "Your daughter's name?", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "howDecidedName", label: "How did you/your partner decide upon that name?", type: "textarea", placeholder: "Family tradition, favourite name..." },
  { id: "dayBorn", label: "What do you remember about the day she was born?", type: "textarea", placeholder: "The emotions, the setting..." },
  { id: "earliestMemory", label: "Apart from that what is your earliest memory of her?", type: "textarea", placeholder: "A moment that stayed with you" },
  { id: "characterYoung", label: "What was her character like when she was little?", type: "textarea", placeholder: "Shy? Bossy? Always performing?" },
  { id: "characterNow", label: "Has she continued to be that character in later life?", type: "textarea", placeholder: "How has she evolved?" },
  { id: "passionsGrowingUp", label: "What were her passions when she was growing up?", type: "textarea", placeholder: "Dance, horses, football..." },
  { id: "passionsNow", label: "What are her passions now?", type: "textarea", placeholder: "Career, hobbies, causes..." },
  { id: "thingsTogether", label: "What kind of things did you do together?", type: "textarea", placeholder: "Activities, traditions, routines..." },
  { id: "traitsFromYou", label: "What part of her traits has she inherited from you?", type: "textarea", placeholder: "Stubbornness? Sense of humour?" },
  { id: "traitsFromMother", label: "What has she inherited from her mother?", type: "textarea", placeholder: "Kindness? Determination?" },
  { id: "firstTriumphs", label: "What were her first big triumphs and successes?", type: "textarea", placeholder: "Awards, achievements, proud moments..." },
  { id: "childhoodStory", label: "Is there one story from her childhood that sticks out?", type: "textarea", placeholder: "The one you always tell" },
  { id: "excelledAtSchool", label: "What did she excel at, at school?", type: "textarea", placeholder: "Subjects, sports, social..." },
  { id: "notEnjoySchool", label: "What did she really not enjoy at school?", type: "textarea", placeholder: "Maths? PE? Early mornings?" },
  { id: "wentToUni", label: "Did your daughter go to university or college?", type: "yesno" },
  { id: "uniDetails", label: "Which university or college did she attend, and what course did she study?", type: "textarea", conditionField: "wentToUni", conditionValue: "Yes" },
  { id: "career", label: "What career did your daughter embark on?", type: "text", placeholder: "e.g. Marketing, teaching, medicine" },
  { id: "adultAchievements", label: "What are her biggest achievements as an adult?", type: "textarea", placeholder: "Professional, personal, creative..." },
  { id: "groomName", label: "What is the name of her husband to be?", type: "text", required: true, placeholder: "e.g. Tom" },
  { id: "groomParents", label: "Names of his parents?", type: "text", placeholder: "e.g. David and Jane" },
  { id: "firstMeetingGroom", label: "What was your first meeting with him like?", type: "textarea", placeholder: "First impressions, the setting..." },
  { id: "groomCharacter", label: "What sort of character is he?", type: "textarea", placeholder: "Funny? Kind? Quiet?" },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true, placeholder: "The full story" },
  { id: "suitableCouple", label: "What makes them such a suitable couple?", type: "textarea", placeholder: "What works about them together?" },
  { id: "hasChildren", label: "Does your daughter have children?", type: "yesno" },
  { id: "childrenNames", label: "What are their names?", type: "text", conditionField: "hasChildren", conditionValue: "Yes" },
  { id: "engagementFeelings", label: "Succinctly describe your feelings when they announced their engagement.", type: "textarea", placeholder: "Joy? Relief? A funny reaction?" },
  { id: "absentFriends", label: "Would you like to make a toast to absent friends?", type: "yesno" },
  { id: "absentFriendsDetails", label: "Tell me about them", type: "textarea", conditionField: "absentFriends", conditionValue: "Yes" },
];

export const motherOfBrideQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. Mary" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Smith" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "husbandName", label: "Your daughter's father's name?", type: "text", required: true, placeholder: "e.g. John" },
  { id: "fatherDeceased", label: "Is your daughter's father deceased?", type: "yesno" },
  { id: "marriedUntilDemise", label: "Were you married until his demise?", type: "yesno", conditionField: "fatherDeceased", conditionValue: "Yes" },
  { id: "stillMarried", label: "Are you still married?", type: "yesno", conditionField: "fatherDeceased", conditionValue: "No" },
  { id: "hasPartner", label: "Do you have a long term partner?", type: "yesno", conditionField: "stillMarried", conditionValue: "No" },
  { id: "partnerName", label: "What is your partner's name?", type: "text", conditionField: "hasPartner", conditionValue: "Yes" },
  { id: "daughterName", label: "Your daughter's name?", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "howDecidedName", label: "How did you/your partner decide upon that name?", type: "textarea" },
  { id: "dayBorn", label: "What do you remember about the day she was born?", type: "textarea" },
  { id: "earliestMemory", label: "Apart from that what is your earliest memory of her?", type: "textarea" },
  { id: "characterYoung", label: "What was her character like when she was little?", type: "textarea" },
  { id: "characterNow", label: "Has she continued to be that character in later life?", type: "textarea" },
  { id: "passionsGrowingUp", label: "What were her passions when she was growing up?", type: "textarea" },
  { id: "passionsNow", label: "What are her passions now?", type: "textarea" },
  { id: "thingsTogether", label: "What kind of things did you do together?", type: "textarea" },
  { id: "traitsFromYou", label: "What part of her traits has she inherited from you?", type: "textarea" },
  { id: "traitsFromFather", label: "What has she inherited from her father?", type: "textarea" },
  { id: "firstTriumphs", label: "What were her first big triumphs and successes?", type: "textarea" },
  { id: "childhoodStory", label: "Is there one story from her childhood that sticks out?", type: "textarea" },
  { id: "excelledAtSchool", label: "What did she excel at, at school?", type: "textarea" },
  { id: "notEnjoySchool", label: "What did she really not enjoy at school?", type: "textarea" },
  { id: "wentToUni", label: "Did your daughter go to university or college?", type: "yesno" },
  { id: "uniDetails", label: "Which university or college did she attend, and what course did she study?", type: "textarea", conditionField: "wentToUni", conditionValue: "Yes" },
  { id: "career", label: "What career did your daughter embark on?", type: "text" },
  { id: "adultAchievements", label: "What are her biggest achievements as an adult?", type: "textarea" },
  { id: "groomName", label: "What is the name of her husband to be?", type: "text", required: true },
  { id: "groomParents", label: "Names of his parents?", type: "text" },
  { id: "firstMeetingGroom", label: "What was your first meeting with him like?", type: "textarea" },
  { id: "groomCharacter", label: "What sort of character is he?", type: "textarea" },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true },
  { id: "suitableCouple", label: "What makes them such a suitable couple?", type: "textarea" },
  { id: "hasChildren", label: "Does your daughter have children?", type: "yesno" },
  { id: "childrenNames", label: "What are their names?", type: "text", conditionField: "hasChildren", conditionValue: "Yes" },
  { id: "engagementFeelings", label: "Succinctly describe your feelings when they announced their engagement.", type: "textarea" },
  { id: "absentFriends", label: "Would you like to make a toast to absent friends?", type: "yesno" },
  { id: "absentFriendsDetails", label: "Tell me about them", type: "textarea", conditionField: "absentFriends", conditionValue: "Yes" },
];

export const maidOfHonourQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. Emma" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Taylor" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "aboutYou", label: "How old are you, what's your job, where do you live etc", type: "textarea" },
  { id: "brideName", label: "The bride's name?", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "howKnowBride", label: "How do you know the bride?", type: "textarea", required: true },
  { id: "firstMet", label: "Do you remember the first time you met?", type: "textarea" },
  { id: "brideCharacter", label: "What type of character is she?", type: "textarea" },
  { id: "passions", label: "What are her passions?", type: "textarea" },
  { id: "funnyStory", label: "Any funny stories about the bride?", type: "textarea", required: true },
  { id: "groomName", label: "What is the groom's name?", type: "text", required: true },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true },
  { id: "groomEffect", label: "What sort of effect has he had on her?", type: "textarea" },
  { id: "whatMakesThemGreat", label: "What makes them a great couple?", type: "textarea" },
  { id: "brideHelpedYou", label: "In what ways has she helped you out in the past?", type: "textarea" },
  { id: "favouriteMemory", label: "What's your favourite memory together?", type: "textarea" },
  { id: "whatAdmire", label: "What do you most admire about her?", type: "textarea" },
  { id: "hasChildren", label: "Does the bride have children?", type: "yesno" },
  { id: "childrenNames", label: "What are their names?", type: "text", conditionField: "hasChildren", conditionValue: "Yes" },
  { id: "closingWish", label: "What's your wish for the happy couple?", type: "textarea" },
];

export const fatherOfGroomQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. David" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Brown" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "wifeName", label: "Your son's mother's name?", type: "text", required: true },
  { id: "stillMarried", label: "Are you still married?", type: "yesno", required: true },
  { id: "hasPartner", label: "Do you have a long term partner?", type: "yesno", conditionField: "stillMarried", conditionValue: "No" },
  { id: "partnerName", label: "What is your partner's name?", type: "text", conditionField: "hasPartner", conditionValue: "Yes" },
  { id: "sonName", label: "Your son's name?", type: "text", required: true },
  { id: "howDecidedName", label: "How did you/your partner decide upon that name?", type: "textarea" },
  { id: "dayBorn", label: "What do you remember about the day he was born?", type: "textarea" },
  { id: "earliestMemory", label: "Apart from that what is your earliest memory of him?", type: "textarea" },
  { id: "characterYoung", label: "What was his character like when he was little?", type: "textarea" },
  { id: "characterNow", label: "Has he continued to be that character in later life?", type: "textarea" },
  { id: "passionsGrowingUp", label: "What were his passions when he was growing up?", type: "textarea" },
  { id: "passionsNow", label: "What are his passions now?", type: "textarea" },
  { id: "thingsTogether", label: "What kind of things did you do together?", type: "textarea" },
  { id: "traitsFromYou", label: "What part of his traits has he inherited from you?", type: "textarea" },
  { id: "traitsFromMother", label: "What has he inherited from his mother?", type: "textarea" },
  { id: "firstTriumphs", label: "What were his first big triumphs and successes?", type: "textarea" },
  { id: "childhoodStory", label: "Is there one story from his childhood that sticks out?", type: "textarea" },
  { id: "excelledAtSchool", label: "What did he excel at, at school?", type: "textarea" },
  { id: "notEnjoySchool", label: "What did he really not enjoy at school?", type: "textarea" },
  { id: "wentToUni", label: "Did your son go to university or college?", type: "yesno" },
  { id: "uniDetails", label: "Which university or college did he attend, and what course did he study?", type: "textarea", conditionField: "wentToUni", conditionValue: "Yes" },
  { id: "career", label: "What career did your son embark on?", type: "text" },
  { id: "adultAchievements", label: "What are his biggest achievements as an adult?", type: "textarea" },
  { id: "brideName", label: "What is the name of his wife to be?", type: "text", required: true },
  { id: "brideParents", label: "Names of her parents?", type: "text" },
  { id: "firstMeetingBride", label: "What was your first meeting with her like?", type: "textarea" },
  { id: "brideCharacter", label: "What sort of character is she?", type: "textarea" },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true },
  { id: "suitableCouple", label: "What makes them such a suitable couple?", type: "textarea" },
  { id: "hasChildren", label: "Does your son have children?", type: "yesno" },
  { id: "childrenNames", label: "What are their names?", type: "text", conditionField: "hasChildren", conditionValue: "Yes" },
  { id: "engagementFeelings", label: "Succinctly describe your feelings when they announced their engagement.", type: "textarea" },
  { id: "absentFriends", label: "Would you like to make a toast to absent friends?", type: "yesno" },
  { id: "absentFriendsDetails", label: "Tell me about them", type: "textarea", conditionField: "absentFriends", conditionValue: "Yes" },
];

export const brotherOfBrideQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. Jack" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Smith" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "aboutYou", label: "How old are you, what's your job, where do you live etc", type: "textarea" },
  { id: "sisterName", label: "Your sister's name?", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "olderOrYounger", label: "Are you older or younger than your sister?", type: "text", placeholder: "e.g. Two years older" },
  { id: "childhoodMemory", label: "What is your favourite childhood memory with her?", type: "textarea", required: true },
  { id: "sisterCharacter", label: "What type of character is she?", type: "textarea" },
  { id: "funnyStory", label: "Any funny stories about your sister?", type: "textarea", required: true },
  { id: "whatAdmire", label: "What do you most admire about her?", type: "textarea" },
  { id: "groomName", label: "What is the groom's name?", type: "text", required: true },
  { id: "firstMeetingGroom", label: "What was your first meeting with him like?", type: "textarea" },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true },
  { id: "whatMakesThemGreat", label: "What makes them a great couple?", type: "textarea" },
  { id: "groomEffect", label: "What sort of effect has he had on her?", type: "textarea" },
  { id: "closingWish", label: "What's your wish for the happy couple?", type: "textarea" },
];

export const motherOfGroomQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. Jane" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Brown" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "husbandName", label: "Your son's father's name?", type: "text", required: true },
  { id: "fatherDeceased", label: "Is your son's father deceased?", type: "yesno" },
  { id: "marriedUntilDemise", label: "Were you married until his demise?", type: "yesno", conditionField: "fatherDeceased", conditionValue: "Yes" },
  { id: "stillMarried", label: "Are you still married?", type: "yesno", conditionField: "fatherDeceased", conditionValue: "No" },
  { id: "hasPartner", label: "Do you have a long term partner?", type: "yesno", conditionField: "stillMarried", conditionValue: "No" },
  { id: "partnerName", label: "What is your partner's name?", type: "text", conditionField: "hasPartner", conditionValue: "Yes" },
  { id: "sonName", label: "Your son's name?", type: "text", required: true },
  { id: "howDecidedName", label: "How did you/your partner decide upon that name?", type: "textarea" },
  { id: "dayBorn", label: "What do you remember about the day he was born?", type: "textarea" },
  { id: "earliestMemory", label: "Apart from that what is your earliest memory of him?", type: "textarea" },
  { id: "characterYoung", label: "What was his character like when he was little?", type: "textarea" },
  { id: "characterNow", label: "Has he continued to be that character in later life?", type: "textarea" },
  { id: "passionsGrowingUp", label: "What were his passions when he was growing up?", type: "textarea" },
  { id: "passionsNow", label: "What are his passions now?", type: "textarea" },
  { id: "thingsTogether", label: "What kind of things did you do together?", type: "textarea" },
  { id: "traitsFromYou", label: "What part of his traits has he inherited from you?", type: "textarea" },
  { id: "traitsFromFather", label: "What has he inherited from his father?", type: "textarea" },
  { id: "firstTriumphs", label: "What were his first big triumphs and successes?", type: "textarea" },
  { id: "childhoodStory", label: "Is there one story from his childhood that sticks out?", type: "textarea" },
  { id: "excelledAtSchool", label: "What did he excel at, at school?", type: "textarea" },
  { id: "notEnjoySchool", label: "What did he really not enjoy at school?", type: "textarea" },
  { id: "wentToUni", label: "Did your son go to university or college?", type: "yesno" },
  { id: "uniDetails", label: "Which university or college did he attend, and what course did he study?", type: "textarea", conditionField: "wentToUni", conditionValue: "Yes" },
  { id: "career", label: "What career did your son embark on?", type: "text" },
  { id: "adultAchievements", label: "What are his biggest achievements as an adult?", type: "textarea" },
  { id: "brideName", label: "What is the name of his bride to be?", type: "text", required: true },
  { id: "brideParents", label: "Names of her parents?", type: "text" },
  { id: "firstMeetingBride", label: "What was your first meeting with her like?", type: "textarea" },
  { id: "brideCharacter", label: "What sort of character is she?", type: "textarea" },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true },
  { id: "suitableCouple", label: "What makes them such a suitable couple?", type: "textarea" },
  { id: "hasChildren", label: "Does your son have children?", type: "yesno" },
  { id: "childrenNames", label: "What are their names?", type: "text", conditionField: "hasChildren", conditionValue: "Yes" },
  { id: "engagementFeelings", label: "Succinctly describe your feelings when they announced their engagement.", type: "textarea" },
  { id: "absentFriends", label: "Would you like to make a toast to absent friends?", type: "yesno" },
  { id: "absentFriendsDetails", label: "Tell me about them", type: "textarea", conditionField: "absentFriends", conditionValue: "Yes" },
];

export const weddingVowsQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "partnerName", label: "Your partner's name?", type: "text", required: true, placeholder: "e.g. Tom" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished vows here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "howMet", label: "How did you meet?", type: "textarea", required: true },
  { id: "whenKnew", label: "When did you know they were the one?", type: "textarea" },
  { id: "whatLove", label: "What do you love most about them?", type: "textarea", required: true },
  { id: "sharedMemory", label: "What is your favourite shared memory?", type: "textarea" },
  { id: "challenges", label: "What challenges have you overcome together?", type: "textarea" },
  { id: "futureDreams", label: "What are your dreams for your future together?", type: "textarea" },
  { id: "promisesToMake", label: "What promises do you want to make?", type: "textarea", required: true, placeholder: "The commitments that matter most to you" },
  { id: "tone", label: "What tone do you want? Romantic, humorous, poetic, or simple?", type: "text", placeholder: "e.g. Romantic with a touch of humour" },
];

export const birthdayQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "birthdayPersonName", label: "Who is the birthday speech for?", type: "text", required: true, placeholder: "e.g. Dad, Sarah, Grandma" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "relationship", label: "What is your relationship to them?", type: "text", required: true, placeholder: "e.g. Son, best friend, colleague" },
  { id: "age", label: "What age are they turning?", type: "text", placeholder: "e.g. 50" },
  { id: "characterDescription", label: "How would you describe their character?", type: "textarea", required: true },
  { id: "favouriteMemory", label: "What is your favourite memory with them?", type: "textarea", required: true },
  { id: "funnyStory", label: "Any funny stories about them?", type: "textarea" },
  { id: "achievements", label: "What are you most proud of about them?", type: "textarea" },
  { id: "passions", label: "What are their passions and interests?", type: "textarea" },
  { id: "wish", label: "What do you wish for them in the year ahead?", type: "textarea" },
  { id: "tone", label: "What tone do you want? Funny, heartfelt, or a mix?", type: "text", placeholder: "e.g. Funny with a heartfelt ending" },
];

export const retirementQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "retireeName", label: "Who is retiring?", type: "text", required: true, placeholder: "e.g. John" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "relationship", label: "What is your relationship to them?", type: "text", required: true, placeholder: "e.g. Colleague, manager, friend" },
  { id: "yearsWorked", label: "How many years have they worked at the company/profession?", type: "text", placeholder: "e.g. 30 years" },
  { id: "role", label: "What was their role?", type: "text", placeholder: "e.g. Head of Sales" },
  { id: "characterDescription", label: "How would you describe their character?", type: "textarea", required: true },
  { id: "achievements", label: "What are their biggest professional achievements?", type: "textarea" },
  { id: "funnyStory", label: "Any funny stories from work?", type: "textarea", required: true },
  { id: "impact", label: "What impact have they had on colleagues and the workplace?", type: "textarea" },
  { id: "retirementPlans", label: "What are their plans for retirement?", type: "textarea" },
  { id: "closingWish", label: "What do you wish for them in retirement?", type: "textarea" },
];

export const anniversaryQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "coupleName", label: "Who is the anniversary speech for?", type: "text", required: true, placeholder: "e.g. Mum and Dad, John and Mary" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "relationship", label: "What is your relationship to them?", type: "text", required: true, placeholder: "e.g. Son, daughter, friend" },
  { id: "yearsMarried", label: "How many years are they celebrating?", type: "text", placeholder: "e.g. 25, 50" },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true },
  { id: "whatMakesThemGreat", label: "What makes them such a great couple?", type: "textarea", required: true },
  { id: "favouriteMemory", label: "What is your favourite memory of them together?", type: "textarea" },
  { id: "funnyStory", label: "Any funny stories about them?", type: "textarea" },
  { id: "challenges", label: "What challenges have they overcome together?", type: "textarea" },
  { id: "closingWish", label: "What do you wish for them?", type: "textarea" },
];

export const eulogyQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "deceasedName", label: "Who is the eulogy for?", type: "text", required: true, placeholder: "e.g. Dad, Grandma, John" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "relationship", label: "What is your relationship to them?", type: "text", required: true, placeholder: "e.g. Son, granddaughter, friend" },
  { id: "age", label: "How old were they?", type: "text", placeholder: "e.g. 82" },
  { id: "characterDescription", label: "How would you describe their character?", type: "textarea", required: true },
  { id: "whatTheyLovedDoing", label: "What did they love doing?", type: "textarea", required: true },
  { id: "favouriteMemory", label: "What is your favourite memory of them?", type: "textarea", required: true },
  { id: "funnyStory", label: "Any funny stories about them?", type: "textarea" },
  { id: "lifeAchievements", label: "What were their biggest achievements or proudest moments?", type: "textarea" },
  { id: "lessonsLearned", label: "What lessons did they teach you?", type: "textarea" },
  { id: "whatYoullMiss", label: "What will you miss most about them?", type: "textarea" },
  { id: "favouriteSaying", label: "Did they have a favourite saying or phrase?", type: "text" },
  { id: "closingMessage", label: "Any final message you want to include?", type: "textarea" },
];

export const graduationQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "graduateName", label: "Who is the speech for?", type: "text", required: true, placeholder: "e.g. My daughter Emily, the class of 2026" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "relationship", label: "What is your relationship to them?", type: "text", required: true, placeholder: "e.g. Parent, teacher, guest speaker" },
  { id: "institution", label: "What school, college, or university?", type: "text", placeholder: "e.g. University of Oxford" },
  { id: "courseOrField", label: "What did they study?", type: "text", placeholder: "e.g. Engineering, Business" },
  { id: "proudMoment", label: "What are you most proud of about them?", type: "textarea", required: true },
  { id: "challenges", label: "What challenges did they overcome?", type: "textarea" },
  { id: "funnyStory", label: "Any funny stories from their time studying?", type: "textarea" },
  { id: "advice", label: "What advice would you give them for the future?", type: "textarea" },
  { id: "closingWish", label: "What do you wish for them?", type: "textarea" },
];

export const babyShowerQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. Emma" },
  { id: "parentNames", label: "Who are the expectant parents?", type: "text", required: true, placeholder: "e.g. Sarah and Tom" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "relationship", label: "What is your relationship to them?", type: "text", required: true, placeholder: "e.g. Best friend, sister, colleague" },
  { id: "babyGender", label: "Do they know the gender? If so, what is it?", type: "text", placeholder: "e.g. Boy, Girl, Surprise" },
  { id: "babyName", label: "Have they chosen a name?", type: "text", placeholder: "e.g. Oliver, or not yet decided" },
  { id: "whatKindOfParent", label: "What kind of parent do you think they will be?", type: "textarea", required: true },
  { id: "favouriteMemory", label: "What is your favourite memory with the parent(s)?", type: "textarea" },
  { id: "funnyStory", label: "Any funny stories about them?", type: "textarea" },
  { id: "advice", label: "Any parenting advice or wishes?", type: "textarea" },
  { id: "closingWish", label: "What do you wish for the new family?", type: "textarea" },
];

export const engagementPartyQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "coupleNames", label: "Names of the engaged couple?", type: "text", required: true, placeholder: "e.g. Sarah and Tom" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "relationship", label: "What is your relationship to them?", type: "text", required: true, placeholder: "e.g. Father, best friend, colleague" },
  { id: "howTheyMet", label: "How did they meet?", type: "textarea", required: true },
  { id: "proposalStory", label: "How did the proposal happen?", type: "textarea" },
  { id: "whatMakesThemGreat", label: "What makes them a great couple?", type: "textarea", required: true },
  { id: "funnyStory", label: "Any funny stories about them?", type: "textarea" },
  { id: "closingWish", label: "What do you wish for them?", type: "textarea" },
];

export const corporateEventQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Wilson" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "role", label: "What is your role/title?", type: "text", required: true, placeholder: "e.g. CEO, Head of Marketing" },
  { id: "companyName", label: "What company or organisation?", type: "text", required: true },
  { id: "eventType", label: "What type of event is it?", type: "text", required: true, placeholder: "e.g. Annual conference, product launch, team dinner" },
  { id: "audience", label: "Who is the audience?", type: "textarea", required: true, placeholder: "e.g. 200 employees, clients, investors" },
  { id: "keyMessage", label: "What is the key message you want to deliver?", type: "textarea", required: true },
  { id: "achievements", label: "Any achievements or milestones to highlight?", type: "textarea" },
  { id: "thanksTo", label: "Anyone you want to thank specifically?", type: "textarea" },
  { id: "tone", label: "What tone do you want? Formal, conversational, inspirational?", type: "text", placeholder: "e.g. Professional but warm" },
  { id: "closingMessage", label: "Any final message or call to action?", type: "textarea" },
];

export const awardsCeremonyQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Wilson" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "presentingOrAccepting", label: "Are you presenting an award or accepting one?", type: "text", required: true, placeholder: "e.g. Presenting, Accepting" },
  { id: "awardName", label: "What is the award called?", type: "text", required: true },
  { id: "recipientName", label: "If presenting, who is the recipient?", type: "text" },
  { id: "recipientAchievements", label: "What are the recipient's key achievements?", type: "textarea" },
  { id: "personalConnection", label: "Do you have a personal connection to the recipient or the award?", type: "textarea" },
  { id: "funnyStory", label: "Any anecdotes or stories to share?", type: "textarea" },
  { id: "thanksTo", label: "Anyone you want to thank?", type: "textarea" },
  { id: "tone", label: "What tone do you want?", type: "text", placeholder: "e.g. Witty and warm, formal and respectful" },
];

export const farewellQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "leaverName", label: "Who is leaving?", type: "text", required: true, placeholder: "e.g. Sarah" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "relationship", label: "What is your relationship to them?", type: "text", required: true, placeholder: "e.g. Colleague, manager, friend" },
  { id: "whereAreTheyGoing", label: "Where are they going?", type: "text", placeholder: "e.g. New job, moving abroad, travelling" },
  { id: "howLongKnown", label: "How long have you known them?", type: "text", placeholder: "e.g. 5 years" },
  { id: "characterDescription", label: "How would you describe their character?", type: "textarea", required: true },
  { id: "favouriteMemory", label: "What is your favourite memory with them?", type: "textarea" },
  { id: "funnyStory", label: "Any funny stories?", type: "textarea" },
  { id: "impact", label: "What impact have they had?", type: "textarea" },
  { id: "closingWish", label: "What do you wish for them?", type: "textarea" },
];

export const golfClubQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Wilson" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "clubName", label: "What is the club or organisation?", type: "text", required: true, placeholder: "e.g. Royal St Andrews Golf Club" },
  { id: "role", label: "What is your role at the club?", type: "text", placeholder: "e.g. Captain, Chairman, Committee Member" },
  { id: "eventType", label: "What is the occasion?", type: "text", required: true, placeholder: "e.g. Annual dinner, Captains day, Prize giving" },
  { id: "audience", label: "Who is the audience?", type: "textarea", placeholder: "e.g. 100 club members, families, and guests" },
  { id: "achievements", label: "Any achievements or highlights from the year to mention?", type: "textarea" },
  { id: "funnyStory", label: "Any funny stories or anecdotes?", type: "textarea", required: true },
  { id: "thanksTo", label: "Anyone you want to thank?", type: "textarea" },
  { id: "tone", label: "What tone do you want?", type: "text", placeholder: "e.g. Witty after dinner style" },
  { id: "closingMessage", label: "Any final message?", type: "textarea" },
];

export const charityGalaQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Wilson" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "charityName", label: "What is the charity or cause?", type: "text", required: true },
  { id: "role", label: "What is your role?", type: "text", placeholder: "e.g. Founder, Patron, Guest speaker" },
  { id: "eventName", label: "What is the event called?", type: "text", placeholder: "e.g. Annual Gala Dinner" },
  { id: "audience", label: "Who is the audience?", type: "textarea", placeholder: "e.g. 300 donors, supporters, and volunteers" },
  { id: "missionStatement", label: "In your own words, what does the charity do?", type: "textarea", required: true },
  { id: "impactStory", label: "Can you share a story that shows the charity's impact?", type: "textarea", required: true },
  { id: "achievements", label: "Any recent achievements or milestones?", type: "textarea" },
  { id: "callToAction", label: "What do you want the audience to do?", type: "textarea", placeholder: "e.g. Donate, volunteer, spread the word" },
  { id: "thanksTo", label: "Anyone you want to thank?", type: "textarea" },
  { id: "tone", label: "What tone do you want?", type: "text", placeholder: "e.g. Inspiring and heartfelt" },
];

export const keynoteQuestions: Question[] = [
  { id: "firstName", label: "Your first name", type: "text", required: true, placeholder: "e.g. James" },
  { id: "surname", label: "Your surname", type: "text", required: true, placeholder: "e.g. Wilson" },
  { id: "email", label: "Your email address", subtitle: "We'll send your finished speech here", type: "email", required: true, placeholder: "you@example.com" },
  { id: "role", label: "What is your role/title?", type: "text", required: true },
  { id: "eventName", label: "What is the event or conference?", type: "text", required: true, placeholder: "e.g. TED, industry summit" },
  { id: "audience", label: "Who is the audience?", type: "textarea", required: true, placeholder: "e.g. 500 tech professionals" },
  { id: "topic", label: "What is the main topic or theme?", type: "textarea", required: true },
  { id: "keyTakeaway", label: "What is the one thing you want the audience to remember?", type: "textarea", required: true },
  { id: "personalStory", label: "Do you have a personal story that relates to the topic?", type: "textarea" },
  { id: "expertise", label: "What gives you authority on this topic?", type: "textarea" },
  { id: "callToAction", label: "What do you want the audience to do after your talk?", type: "textarea" },
  { id: "tone", label: "What tone do you want?", type: "text", placeholder: "e.g. Thought provoking, energetic, conversational" },
  { id: "speechLength", label: "How long should the speech be?", type: "text", placeholder: "e.g. 10 minutes, 20 minutes" },
];

export const SPEECH_TYPE_CONFIGS: Record<string, SpeechTypeConfig> = {
  "best-man": { id: "best-man", title: "Best Man Speech", description: "Funny, heartfelt, and perfectly pitched.", questions: bestManQuestions },
  "groom": { id: "groom", title: "Groom's Speech", description: "Thank everyone who matters and set the tone.", questions: groomQuestions },
  "bride": { id: "bride", title: "Bride's Speech", description: "Your moment to speak from the heart.", questions: brideQuestions },
  "father-of-bride": { id: "father-of-bride", title: "Father of the Bride", description: "Pride, humour, and a tear or two.", questions: fatherOfBrideQuestions },
  "mother-of-bride": { id: "mother-of-bride", title: "Mother of the Bride", description: "A heartfelt tribute filled with love and memories.", questions: motherOfBrideQuestions },
  "brother-of-bride": { id: "brother-of-bride", title: "Brother of the Bride", description: "Celebrate your sister with warmth and wit.", questions: brotherOfBrideQuestions },
  "maid-of-honour": { id: "maid-of-honour", title: "Maid of Honour", description: "Celebrate your best friend with warmth and wit.", questions: maidOfHonourQuestions },
  "father-of-groom": { id: "father-of-groom", title: "Father of the Groom", description: "Welcome a new family member with warmth and pride.", questions: fatherOfGroomQuestions },
  "mother-of-groom": { id: "mother-of-groom", title: "Mother of the Groom", description: "A heartfelt tribute to your son and his new chapter.", questions: motherOfGroomQuestions },
  "wedding-vows": { id: "wedding-vows", title: "Wedding Vows", description: "Promise forever with deeply personal words.", questions: weddingVowsQuestions },
  "birthday": { id: "birthday", title: "Birthday Speech", description: "Celebrate the year that was and the year ahead.", questions: birthdayQuestions },
  "retirement": { id: "retirement", title: "Retirement Speech", description: "Honour a career well lived.", questions: retirementQuestions },
  "anniversary": { id: "anniversary", title: "Anniversary Speech", description: "Celebrate love that stands the test of time.", questions: anniversaryQuestions },
  "eulogy": { id: "eulogy", title: "Eulogy", description: "A heartfelt tribute to honour a life well lived.", questions: eulogyQuestions },
  "graduation": { id: "graduation", title: "Graduation Speech", description: "Inspire the next chapter with wisdom and heart.", questions: graduationQuestions },
  "baby-shower": { id: "baby-shower", title: "Baby Shower Speech", description: "Welcome the newest arrival with joy and warmth.", questions: babyShowerQuestions },
  "engagement-party": { id: "engagement-party", title: "Engagement Party Speech", description: "Kick off the celebration with the perfect words.", questions: engagementPartyQuestions },
  "corporate-event": { id: "corporate-event", title: "Corporate Event Speech", description: "Confident, polished, and audience appropriate.", questions: corporateEventQuestions },
  "awards-ceremony": { id: "awards-ceremony", title: "Awards Ceremony Speech", description: "Present or accept with charisma and gratitude.", questions: awardsCeremonyQuestions },
  "farewell": { id: "farewell", title: "Farewell Speech", description: "Say goodbye with class and warmth.", questions: farewellQuestions },
  "golf-club": { id: "golf-club", title: "Golf Club / Sports Dinner", description: "Witty after dinner speaking for the clubhouse crowd.", questions: golfClubQuestions },
  "charity-gala": { id: "charity-gala", title: "Charity Gala Speech", description: "Inspire generosity with a speech that moves the room.", questions: charityGalaQuestions },
  "keynote": { id: "keynote", title: "Keynote / Conference Speech", description: "Open or close an event with impact and authority.", questions: keynoteQuestions },
};
