import { Link } from "react-router-dom";

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-gradient-warm">
      <nav className="bg-charcoal">
        <div className="container mx-auto px-6 py-4">
          <Link to="/" className="font-display text-xl font-bold text-primary-foreground">
            bestmanspeech.com
          </Link>
        </div>
      </nav>

      <div className="container mx-auto px-6 py-16 max-w-3xl">
        <h1 className="font-display text-4xl font-bold text-foreground mb-8">Terms &amp; Conditions</h1>
        <p className="font-body text-muted-foreground text-sm mb-8">Last updated: {new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p>

        <div className="prose-custom space-y-8">
          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">1. Introduction</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              These terms and conditions govern your use of the bestmanspeech.com website and services. By using our service, you agree to be bound by these terms. If you do not agree, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">2. The Service</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              bestmanspeech.com provides an AI powered speech writing service. You provide personal details and stories via our questionnaire, and we generate a personalised speech for your chosen occasion. The speech is generated using artificial intelligence and refined based on professional speechwriting methodology.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">3. Ordering and Payment</h2>
            <ul className="list-disc pl-6 space-y-2 font-body text-muted-foreground">
              <li>All prices are displayed in the currency shown at checkout and include applicable taxes.</li>
              <li>Payment is processed securely via Stripe. We do not store your card details.</li>
              <li>Your speech will be made available to you immediately after successful payment.</li>
              <li>By completing a purchase, you agree to these terms and acknowledge that you are purchasing a digital product.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">4. Refund Policy</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              As our product is a digital service delivered immediately upon payment, we do not offer automatic refunds. However, if you are genuinely dissatisfied with the quality of your speech, please contact us and we will work with you to resolve the issue. We may offer a revised speech or a partial refund at our discretion.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">5. Intellectual Property</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              Once you have purchased a speech, you are granted a personal, non exclusive licence to use that speech for its intended purpose (e.g. delivering it at an event). You may not resell, redistribute, or commercially exploit the generated speeches. The underlying technology, methodology, and website content remain our intellectual property.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">6. Your Responsibilities</h2>
            <ul className="list-disc pl-6 space-y-2 font-body text-muted-foreground">
              <li>You must provide accurate and truthful information in the questionnaire.</li>
              <li>You are responsible for reviewing and editing the speech before delivery.</li>
              <li>You must not use our service for any unlawful, defamatory, or harmful purpose.</li>
              <li>You must be at least 18 years old to use our service.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">7. Disclaimer</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              While we strive to produce high quality speeches, we cannot guarantee that every speech will meet your expectations without any editing. Speeches are generated by AI and should be reviewed, personalised further, and rehearsed before delivery. We are not liable for the reception of any speech at an event.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">8. Limitation of Liability</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              To the fullest extent permitted by law, our total liability for any claim arising from or related to our service shall not exceed the amount you paid for the specific speech in question. We shall not be liable for any indirect, incidental, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">9. Data Protection</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              Your personal data is handled in accordance with our <Link to="/privacy" className="text-accent hover:text-gold-dark underline">Privacy Policy</Link>. By using our service, you acknowledge that you have read and understood our privacy practices.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">10. Modifications</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              We reserve the right to update these terms at any time. Changes will be posted on this page with an updated revision date. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">11. Governing Law</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              These terms are governed by and construed in accordance with the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">12. Contact</h2>
            <p className="font-body text-muted-foreground leading-relaxed">
              If you have any questions about these terms, please contact us at the email address provided on our website.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border">
          <Link to="/" className="font-body text-accent hover:text-gold-dark text-sm transition-colors">
            ← Back to home
          </Link>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
